Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jupyter_cache/executors/utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/nbclient/client.py", line 554, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import matplotlib.pyplot as plt  # importar a bilioteca pyplot para fazer gr√°ficos
from matplotlib import colors
#Comandos opcionais para formatar gr√°fico
font = {'family' : 'Arial',
        'weight' : 'normal',
        'size'   : 12}	
lines = {'linewidth' : 3.0}
figure = {'figsize' : [6.0, 6/1.6]}
matplotlib.rc('font', **font)
matplotlib.rc('lines', **lines)
matplotlib.rc('figure', **figure)

import numpy as np   # importar a biblioteca Numpy para lidar com matrizes
import pandas as pd   # importa bilioteca pandas para  lidar com processamento de dados
import os #com
import glob
from scipy.optimize import curve_fit # pacote para ajuste de curvas
# navegar pelas pastas
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
[0;32m<ipython-input-1-74a53e444528>[0m in [0;36m<module>[0;34m[0m
[1;32m      7[0m [0mlines[0m [0;34m=[0m [0;34m{[0m[0;34m'linewidth'[0m [0;34m:[0m [0;36m3.0[0m[0;34m}[0m[0;34m[0m[0;34m[0m[0m
[1;32m      8[0m [0mfigure[0m [0;34m=[0m [0;34m{[0m[0;34m'figsize'[0m [0;34m:[0m [0;34m[[0m[0;36m6.0[0m[0;34m,[0m [0;36m6[0m[0;34m/[0m[0;36m1.6[0m[0;34m][0m[0;34m}[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 9[0;31m [0mmatplotlib[0m[0;34m.[0m[0mrc[0m[0;34m([0m[0;34m'font'[0m[0;34m,[0m [0;34m**[0m[0mfont[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     10[0m [0mmatplotlib[0m[0;34m.[0m[0mrc[0m[0;34m([0m[0;34m'lines'[0m[0;34m,[0m [0;34m**[0m[0mlines[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m     11[0m [0mmatplotlib[0m[0;34m.[0m[0mrc[0m[0;34m([0m[0;34m'figure'[0m[0;34m,[0m [0;34m**[0m[0mfigure[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;31mNameError[0m: name 'matplotlib' is not defined
NameError: name 'matplotlib' is not defined

